#! perl

# A slightly modified version of the urxvt-fullscreen package (see
# https://aur.archlinux.org/packages/urxvt-fullscreen/).
sub on_user_command {
	my ($self, $cmd) = @_;
	if ($cmd eq "fullscreen:switch") {
		my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen` ;
	}
}
